workflows:
  main-workflow:
    name: Final Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Initialize Android
        script: flutter create . --platforms=android
      - name: Get Packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/**/app-release.apk
